#
# Projekt: BIN
# Autor:   Lenka Turonova, xturon02
# Datum:   12.4.2014
#

TARGET=main

${TARGET}:	${TARGET}.c
	gcc -std=c99 -O2 -o ${TARGET} ${TARGET}.c -lm

run:
	./${TARGET}
    
clean:
	rm -f ${TARGET}